backend/controllers/HousesController.php
<?php

namespace backend\controllers;

use Yii;
use linslin\yii2\curl;
use common\components\ApiHelper;
use yii\filters\AccessControl;
use common\models\House;
use yii\web\UploadedFile;
use common\components\UserApiLoggedFilter;

class HousesController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            [
                'class' => UserApiLoggedFilter::className(),
                'only' => ['index', 'ajax-load-sorting-result', 'search', 'category', 'view', 'create', 'update'],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'ajax-load-sorting-result', 'search', 'category', 'view', 'create', 'update'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'ajax-load-sorting-result', 'search', 'category', 'view', 'create', 'update'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
    /**
     * @return string
     */
    public function actionIndex($sortBy = '')
    {
        $sortingResults = ApiHelper::getHomeResultsFilterOptions();
        $baseParams = ApiHelper::defaultAllPropertiesParams();

        //get all properties
         /*   if(!empty($sortBy) && !empty($sortingResults[$sortBy])) {               
                $baseParams['sortBy'] = $sortBy;
                $allHouses =  ApiHelper::getAllProperties($baseParams);
            } else {
                //todo : custom later while integrating pagination
                $allHouses =  ApiHelper::getAllProperties();
            }*/
            
        //get active properties
            $baseParams['active'] = true;
            $activeProperties = ApiHelper::getAllProperties($baseParams, false);
            
        //get not active properties
            $baseParams['active'] = false;
            $notActiveProperties = ApiHelper::getAllProperties($baseParams, false);
            
        //get not active properties
            unset($baseParams['active']);
            $baseParams['deleted'] = true;
            $deletedProperties = ApiHelper::getAllProperties($baseParams);   
            
        //get archived properties
            $archivedProperties = ApiHelper::getArchiveProperties();
            //var_dump($archivedProperties);
            //exit();
            $allHouses = array_merge($activeProperties, $notActiveProperties);            
            
        return $this->render('index', [
            'allHouses' => $allHouses,
            'activeProperties' => $activeProperties,
            'notActiveProperties' => $notActiveProperties,
            'deletedProperties' => $archivedProperties
        ]);
    }

    /**
     * @param type $sortBy
     * @return type
     */
    public function actionAjaxLoadSortingResult($sortBy='')
    {
        $baseParams = ApiHelper::defaultAllPropertiesParams();
        $baseParams['sortBy'] = $sortBy;
        $results =  ApiHelper::getAllProperties($baseParams);
        $output = $this->renderPartial('_results_list', [
            'results' => $results
        ]);

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return [
            'status' => 'success',
            'data' => $output
        ];
    }

    /**
     * search properties which match requests from user by calling related api
     * @return string
     */
    public function actionSearch($viewType = 'listview')
    {
        $post = $_POST;
        //
        $housingType = $post['search_panel_housingtype'];
        $roomCount = $post['search_panel_room_count'];
        $town = $post['search_panel_town'];
        $zone = $post['search_panel_zone'];
        $price_min = $post['search_panel_price_min'];
        $price_max = $post['search_panel_price_max'];
        $area_min = $post['search_panel_surface_min'];
        $area_max = $post['search_panel_surface_max'];
        $keywords = $post['search_panel_keyword'];
        $publication_date = $post['search_panel_publication_date'];
        $radius = $post['search_panel_radius'];

        //parameters to be sent to api
        $params = [
            'housingType' => $housingType,
            'roomCount' => $roomCount,
            'town' => $town,
            'zone' => $zone,
            'radius' => $radius,
            'priceMin' => (int) $price_min,
            'priceMax' => (int) $price_max,
            'roomSizeMin' => (int) $area_min,
            'roomSizeMax' => (int) $area_max,
            'keyword' => $keywords,
            'publicationDate' => $publication_date
        ];
		//echo '<pre>';
       // print_r($params);
		//echo '</pre>';
        //call api with these paramaters
        $curl = new curl\Curl();
        $searchQuery = json_encode($params);
        //
        $results = [];
        //var_dump($searchQuery);
        $response = $curl->setRequestBody($searchQuery)
            ->setHeaders([
                'Content-Type' => 'application/json',
                'Content-Length' => strlen($searchQuery)
            ])
            ->post(ApiHelper::API_URL . ApiHelper::SEARCH_HOUSE_URL);

        $data = json_decode($response, true);
        //print_r($data);exit();
        if(!empty($data['_embedded']))
            $results = $data['_embedded']['houses'];

        //get search data
        $searchData = ApiHelper::buildSearchData();

        $viewType = (in_array($viewType, ApiHelper::resultDisplayMode())) ? $viewType : ApiHelper::LIST_VIEW_MODE;

        return $this->render('search', [
            'results' => $results,
            'searchData' => $searchData,
            'searchedParams' => $params,
            'viewType' => $viewType
        ]);
    }

    /**
     * @return string
     */
    public function actionCategory($id, $viewType = 'listview')
    {
        /**
         * Retrive properties
         */
        $curl = new curl\Curl();
        $params = ApiHelper::getCategoryPropertyParams();
        $params['housingType'] = $id;
        $encodedParams = json_encode($params);
        $response = $curl->setRequestBody($encodedParams)
            ->setHeaders([
                'Content-Type' => 'application/json',
                'Content-Length' => strlen($encodedParams)
            ])
            ->post(ApiHelper::API_URL . ApiHelper::LIST_HOUSE_WITH_PAGINATION_URL);

        $data = json_decode($response, true);
        //var_dump($encodedParams);exit();
        if(!empty($data['_embedded']))
            $results = $data['_embedded']['houses'];
        else
            $results = [];

        //var_dump($results);

        //get search data
        $searchData = ApiHelper::buildSearchData();

        $viewType = (in_array($viewType, ApiHelper::resultDisplayMode())) ? $viewType : ApiHelper::LIST_VIEW_MODE;

        //var_dump($houses);exit();
        return $this->render('category', [
            'results' => $results,
            'searchData' => $searchData,
            'searchedParams' => $params,
            'id' => $id,
            'viewType' => $viewType
        ]);
    }

    /**
     * view details about one property
     * @return string
     */
    public function actionView($id)
    {
        $loadedProperty = ApiHelper::viewProperty($id);
        if(!empty($loadedProperty)) {
            return $this->render('view', [
                'house' => $loadedProperty
            ]);            
        } else {
            throw new Exception("Ce Logement n'existe pas!!!");
        }
    }

    /**
     * submit new property to us
     * @return string
     */
    public function actionCreate() {
        $data = [];
        
        //model
            $model = new House;
        
        //get search data
            $data['questions'] = ApiHelper::buildSearchData(); 
            
        //get dropdowns options
            $data['options'] = [
                'payment_modes' => House::payment_modes,
                'electricity_count_types' => House::electricity_counter_types,
                'shower_types' => House::shower_types
            ];
            
        //
            if($model->load(Yii::$app->request->post())) {
                $model->pictures = UploadedFile::getInstances($model, 'pictures');
                if($model->validate()) {
                    
                } else {
                    var_dump($model->errors);
                }
                
                exit();
            }
            
        return $this->render('create', [
            'data' => $data,
            'model' => $model
        ]);
    }
    
    /**
     * update property data
     */
    public function actionUpdate($id) {
        $loadedProperty = ApiHelper::viewProperty($id);
        if(!empty($loadedProperty)) {
            //var_dump($loadedProperty);exit();
            //model
            $model = new House;
            $model->attributes = $loadedProperty;
            
        //get search data
            $data['questions'] = ApiHelper::buildSearchData(); 
            
        //get dropdowns options
            $data['options'] = [
                'payment_modes' => House::payment_modes,
                'electricity_count_types' => House::electricity_counter_types,
                'shower_types' => House::shower_types
            ];
            
            return $this->render('update', [
                'model' => $model,
                'data' => $data
            ]); 
        } else {
            throw new Exception("Ce Logement n'existe pas!!!");
        }
    }

    public function actionDelete($id) {
        $response = ApiHelper::deleteHouse($id);
        if($response["content"]["House deleted: "] === true) {//house properly deleted
            $output = [
                'status' => 'success',
                'message' => 'Le logement ' . $id  . ' a été correctement supprimé.'
            ];
        } else {
            $output = [

backend/controllers/RayonController.php
<?php

namespace backend\controllers;
use common\components\ApiHelper;

class RayonController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $models = ApiHelper::loadSingleQuestions(ApiHelper::SEARCH_PANEL_RAYON);
        return $this->render('index', [
            'models' => $models
        ]);
    }

}

backend/controllers/VilleController.php
<?php

namespace backend\controllers;
use common\components\ApiHelper;

class VilleController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $models = ApiHelper::loadSingleQuestions(ApiHelper::SEARCH_PANEL_TOWN);
        return $this->render('index', [
            'models' => $models
        ]);
    }

}

backend/controllers/ZoneController.php
<?php

namespace backend\controllers;
use common\components\ApiHelper;

class ZoneController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $models = ApiHelper::loadSingleQuestions(ApiHelper::SEARCH_PANEL_ZONE);
        return $this->render('index', [
            'models' => $models
        ]);
    }

}

backend/views/layouts/__main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/login.php
<?php
use yii\helpers\Html;

use backend\assets\AppAsset;
    AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= Html::encode($this->title) ?></title>
        <!-- Favicon-->
        <link rel="icon" href="../../favicon.ico" type="image/x-icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

        <?= Html::csrfMetaTags() ?>
        <?php $this->head() ?>
    </head>
    <body class="login-page">
        <?php $this->beginBody() ?>
            <?= $content ?>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php
/**
 * Created by PhpStorm.
 * User: Ghislain KPOMASSE
 * Date: 24/03/2018
 * Time: 22:09
 */

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\helpers\Url;
use backend\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">		
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">	
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.animate.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.brighttheme.css"/>
    <!-- JavaScript -->
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/alertify.min.js"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/alertify.min.css"/>
    <!-- Default theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/themes/default.min.css"/>
    <!-- Semantic UI theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/themes/semantic.min.css"/>
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/themes/bootstrap.min.css"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>
</head>
<body class="theme-red">
<?php $this->beginBody() ?>
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>
<!-- #END# Page Loader -->
<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->
<!-- Search Bar -->
<div class="search-bar">
    <div class="search-icon">
        <i class="material-icons">search</i>
    </div>
    <input type="text" placeholder="START TYPING...">
    <div class="close-search">
        <i class="material-icons">close</i>
    </div>
</div>
<!-- #END# Search Bar -->
<!-- Top Bar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="<?= Url::to(['site/index']) ?>"><?= Yii::$app->name?></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Call Search -->
                <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>
                <!-- #END# Call Search -->
                <!-- Notifications -->
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        <i class="material-icons">notifications</i>
                        <span class="label-count">0</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">NOTIFICATIONS</li>
                        <li class="body">
                            <ul class="menu"></ul>
                        </li>
                        <li class="footer">
                            <a href="javascript:void(0);">Notifications</a>
                        </li>
                    </ul>
                </li>
                <!-- #END# Notifications -->
                <li><a href="<?= Url::to(['site/logout']) ?>" data-method="post"><i class="material-icons">settings_power</i></a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- #Top Bar -->
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="image">
                <img src="<?=\yii\helpers\Url::home(true)?>/images/user.png" width="48" height="48" alt="User" />
            </div>
            <div class="info-container">
                <?php if(!Yii::$app->user->isGuest) :?>
                    <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?=Yii::$app->user->identity->firstName;?> <?=Yii::$app->user->identity->surName;?></div>
                    <div class="email"><?=Yii::$app->user->identity->email?></div>
                <?php endif;?>
            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">MENU</li>
                <li class="active">
                    <a href="<?=Url::to(["site/index"]);?>">
                        <i class="material-icons">home</i>
                        <span>Acceuil</span>
                    </a>
                </li>
                <li>
                    <a href="<?=Yii::$app->urlManager->createUrl("houses/index");?>">
                        <i class="material-icons">turned_in</i>
                        <span>Logements</span>
                    </a>
                </li>	
                <li>
                    <a href="<?=Yii::$app->urlManager->createUrl("category/index");?>">
                        <i class="material-icons">turned_in</i>
                        <span>Catégories</span>
                    </a>
                </li>            
                <li>
                    <a href="<?=Yii::$app->urlManager->createUrl("zone/index");?>">
                        <i class="material-icons">add_location</i>
                        <span>Zones</span>
                    </a>
                </li>     
                <li>
                    <a href="<?=Yii::$app->urlManager->createUrl("ville/index");?>">
                        <i class="material-icons">add_location</i>
                        <span>Villes</span>
                    </a>
                </li>   
                <li>
                    <a href="<?=Yii::$app->urlManager->createUrl("rayon/index");?>">
                        <i class="material-icons">add_location</i>
                        <span>Rayons</span>
                    </a>
                </li>                    
            </ul>
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        <div class="legal">
            <div class="copyright">
                &copy; <?=date('Y');?> <a href="javascript:void(0);">Rental House Web</a>.
            </div>
            <div class="version">
                <b>Version: </b> <?=Yii::$app->params['backOfficeVersion']?>
            </div>
        </div>
        <!-- #Footer -->
    </aside>
    <!-- #END# Left Sidebar -->
    <?php /*
    <!-- Right Sidebar -->
    <aside id="rightsidebar" class="right-sidebar">
        <ul class="nav nav-tabs tab-nav-right" role="tablist">
            <li role="presentation" class="active"><a href="#skins" data-toggle="tab">ACTIONS</a></li>
            <li role="presentation"><a href="#settings" data-toggle="tab">SETTINGS</a></li>
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active in active" id="skins">
                <ul class="demo-choose-skin">
                    <li>
                        <a data-method="post" href="<?=Yii::$app->urlManager->createUrl("admin/default/logout");?>" >Logout</a>
                    </li>
                </ul>
            </div>
            <div role="tabpanel" class="tab-pane fade" id="settings">
                <div class="demo-settings">
                    <p>GENERAL SETTINGS</p>
                    <ul class="setting-list">
                        <li>
                            <span>Report Panel Usage</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                        <li>
                            <span>Email Redirect</span>
                            <div class="switch">
                                <label><input type="checkbox"><span class="lever"></span></label>
                            </div>
                        </li>
                    </ul>
                    <p>SYSTEM SETTINGS</p>
                    <ul class="setting-list">
                        <li>
                            <span>Notifications</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                        <li>
                            <span>Auto Updates</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                    </ul>
                    <p>ACCOUNT SETTINGS</p>
                    <ul class="setting-list">
                        <li>
                            <span>Offline</span>
                            <div class="switch">
                                <label><input type="checkbox"><span class="lever"></span></label>
                            </div>
                        </li>
                        <li>
                            <span>Location Permission</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </aside>
    <!-- #END# Right Sidebar -->
    */ ?>
</section>
<section class="content">
    <?= $content ?>
</section>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>