backend/controllers/HousesController.php
<?php

namespace backend\controllers;

use Yii;
use linslin\yii2\curl;
use common\components\ApiHelper;
use yii\filters\AccessControl;
use common\models\House;
use yii\web\UploadedFile;
use common\components\UserApiLoggedFilter;

class HousesController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            [
                'class' => UserApiLoggedFilter::className(),
                'only' => ['index', 'ajax-load-sorting-result', 'search', 'category', 'view', 'create', 'update'],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'ajax-load-sorting-result', 'search', 'category', 'view', 'create', 'update'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'ajax-load-sorting-result', 'search', 'category', 'view', 'create', 'update'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
    /**
     * @return string
     */
    public function actionIndex($sortBy = '')
    {
        $sortingResults = ApiHelper::getHomeResultsFilterOptions();
        $baseParams = ApiHelper::defaultAllPropertiesParams();

        //get all properties
         /*   if(!empty($sortBy) && !empty($sortingResults[$sortBy])) {               
                $baseParams['sortBy'] = $sortBy;
                $allHouses =  ApiHelper::getAllProperties($baseParams);
            } else {
                //todo : custom later while integrating pagination
                $allHouses =  ApiHelper::getAllProperties();
            }*/
            
        //get active properties
            $baseParams['active'] = true;
            $activeProperties = ApiHelper::getAllProperties($baseParams, false);
            
        //get not active properties
            $baseParams['active'] = false;
            $notActiveProperties = ApiHelper::getAllProperties($baseParams, false);
            
        //get not active properties
            unset($baseParams['active']);
            $baseParams['deleted'] = true;
            $deletedProperties = ApiHelper::getAllProperties($baseParams);   
            
        //get archived properties
            $archivedProperties = ApiHelper::getArchiveProperties();
            //var_dump($archivedProperties);
            //exit();
            $allHouses = array_merge($activeProperties, $notActiveProperties);            
            
        return $this->render('index', [
            'allHouses' => $allHouses,
            'activeProperties' => $activeProperties,
            'notActiveProperties' => $notActiveProperties,
            'deletedProperties' => $archivedProperties
        ]);
    }

    /**
     * @param type $sortBy
     * @return type
     */
    public function actionAjaxLoadSortingResult($sortBy='')
    {
        $baseParams = ApiHelper::defaultAllPropertiesParams();
        $baseParams['sortBy'] = $sortBy;
        $results =  ApiHelper::getAllProperties($baseParams);
        $output = $this->renderPartial('_results_list', [
            'results' => $results
        ]);

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return [
            'status' => 'success',
            'data' => $output
        ];
    }

    /**
     * search properties which match requests from user by calling related api
     * @return string
     */
    public function actionSearch($viewType = 'listview')
    {
        $post = $_POST;
        //
        $housingType = $post['search_panel_housingtype'];
        $roomCount = $post['search_panel_room_count'];
        $town = $post['search_panel_town'];
        $zone = $post['search_panel_zone'];
        $price_min = $post['search_panel_price_min'];
        $price_max = $post['search_panel_price_max'];
        $area_min = $post['search_panel_surface_min'];
        $area_max = $post['search_panel_surface_max'];
        $keywords = $post['search_panel_keyword'];
        $publication_date = $post['search_panel_publication_date'];
        $radius = $post['search_panel_radius'];

        //parameters to be sent to api
        $params = [
            'housingType' => $housingType,
            'roomCount' => $roomCount,
            'town' => $town,
            'zone' => $zone,
            'radius' => $radius,
            'priceMin' => (int) $price_min,
            'priceMax' => (int) $price_max,
            'roomSizeMin' => (int) $area_min,
            'roomSizeMax' => (int) $area_max,
            'keyword' => $keywords,
            'publicationDate' => $publication_date
        ];
		//echo '<pre>';
       // print_r($params);
		//echo '</pre>';
        //call api with these paramaters
        $curl = new curl\Curl();
        $searchQuery = json_encode($params);
        //
        $results = [];
        //var_dump($searchQuery);
        $response = $curl->setRequestBody($searchQuery)
            ->setHeaders([
                'Content-Type' => 'application/json',
                'Content-Length' => strlen($searchQuery)
            ])
            ->post(ApiHelper::API_URL . ApiHelper::SEARCH_HOUSE_URL);

        $data = json_decode($response, true);
        //print_r($data);exit();
        if(!empty($data['_embedded']))
            $results = $data['_embedded']['houses'];

        //get search data
        $searchData = ApiHelper::buildSearchData();

        $viewType = (in_array($viewType, ApiHelper::resultDisplayMode())) ? $viewType : ApiHelper::LIST_VIEW_MODE;

        return $this->render('search', [
            'results' => $results,
            'searchData' => $searchData,
            'searchedParams' => $params,
            'viewType' => $viewType
        ]);
    }

    /**
     * @return string
     */
    public function actionCategory($id, $viewType = 'listview')
    {
        /**
         * Retrive properties
         */
        $curl = new curl\Curl();
        $params = ApiHelper::getCategoryPropertyParams();
        $params['housingType'] = $id;
        $encodedParams = json_encode($params);
        $response = $curl->setRequestBody($encodedParams)
            ->setHeaders([
                'Content-Type' => 'application/json',
                'Content-Length' => strlen($encodedParams)
            ])
            ->post(ApiHelper::API_URL . ApiHelper::LIST_HOUSE_WITH_PAGINATION_URL);

        $data = json_decode($response, true);
        //var_dump($encodedParams);exit();
        if(!empty($data['_embedded']))
            $results = $data['_embedded']['houses'];
        else
            $results = [];

        //var_dump($results);

        //get search data
        $searchData = ApiHelper::buildSearchData();

        $viewType = (in_array($viewType, ApiHelper::resultDisplayMode())) ? $viewType : ApiHelper::LIST_VIEW_MODE;

        //var_dump($houses);exit();
        return $this->render('category', [
            'results' => $results,
            'searchData' => $searchData,
            'searchedParams' => $params,
            'id' => $id,
            'viewType' => $viewType
        ]);
    }

    /**
     * view details about one property
     * @return string
     */
    public function actionView($id)
    {
        $loadedProperty = ApiHelper::viewProperty($id);
        if(!empty($loadedProperty)) {
            return $this->render('view', [
                'house' => $loadedProperty
            ]);            
        } else {
            throw new Exception("Ce Logement n'existe pas!!!");
        }
    }

    /**
     * submit new property to us
     * @return string
     */
    public function actionCreate() {
        $data = [];
        
        //model
            $model = new House;
        
        //get search data
            $data['questions'] = ApiHelper::buildSearchData(); 
            
        //get dropdowns options
            $data['options'] = [
                'payment_modes' => House::payment_modes,
                'electricity_count_types' => House::electricity_counter_types,
                'shower_types' => House::shower_types
            ];
            
        //
            if($model->load(Yii::$app->request->post())) {
                $model->pictures = UploadedFile::getInstances($model, 'pictures');
                if($model->validate()) {
                    
                } else {
                    var_dump($model->errors);
                }
                
                exit();
            }
            
        return $this->render('create', [
            'data' => $data,
            'model' => $model
        ]);
    }
    
    /**
     * update property data
     */
    public function actionUpdate($id) {
        $loadedProperty = ApiHelper::viewProperty($id);
        if(!empty($loadedProperty)) {
            //var_dump($loadedProperty);exit();
            //model
            $model = new House;
            $model->attributes = $loadedProperty;
            
        //get search data
            $data['questions'] = ApiHelper::buildSearchData(); 
            
        //get dropdowns options
            $data['options'] = [
                'payment_modes' => House::payment_modes,
                'electricity_count_types' => House::electricity_counter_types,
                'shower_types' => House::shower_types
            ];
            
            return $this->render('update', [
                'model' => $model,
                'data' => $data
            ]); 
        } else {
            throw new Exception("Ce Logement n'existe pas!!!");
        }
    }

    public function actionDelete($id) {
        $response = ApiHelper::deleteHouse($id);
        if($response["content"]["House deleted: "] === true) {//house properly deleted
            $output = [
                'status' => 'success',
                'message' => 'Le logement ' . $id  . ' a été correctement supprimé.'
            ];
        } else {
            $output = [

backend/views/houses/_listhouse.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use common\components\ApiHelper;
?>
<style>
    .table .actions {
        width: 200px
    }
    .table .actions a {
        margin-bottom: 5px;
    }
    .table img {
        width:175px;
        height:120px;
        border: 5px solid silver;
        border-radius: 5px;
    }
</style>
<table class="table">
    <thead>
        <tr>
            <th>Ref.</th>
            <th>Photo</th>
            <th>Titre</th>
            <th>Description</th>
            <th>Prix</th>
            <th>Addresse</th>
            <th>Agent</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($houses as $key=>$house):?>
        <?php
            $agent_contact = (!empty($house['contact'])) ? $house['contact'] : [];
            if (strpos($house['description'], ".") !== false) {
                $description = substr($house['description'], 0, strpos($house['description'], '.')) . "...";
            } else {
                $description = $house['description'];
            }
        ?>                                    
        <tr>                            
            <th scope="row"><?=$house['referenceNumber'];?></th>
            <td>
            <?php if(!empty($house['pictures'])):?>
                <img src="<?= ApiHelper::HOST_URL . ApiHelper::HOUSE_UPLOAD_PATH . SYS_DIRECTORY_SEPARATOR . $house['referenceNumber'];?>/<?= !empty($house['pictures'][0]) ? $house['pictures'][0] : '';?>"/>
            <?php else :?>
                Aucune Image disponible
            <?php endif;?>
            </td>
            <td><?=$house['titel'];?></td>
            <td><?=$description;?></td>
            <td><?=$house['price'];?> <?= Yii::$app->params['localeCurrency'];?>/<?=$house['paymentMode'];?></td>                                        
            <td><?=$house['zone'];?>, <?=$house['town'];?></td>
            <td>
            <?php if(!empty($agent_contact)) : ?>                                           
                <?=$agent_contact['firstName'];?> <?=$agent_contact['surName'];?>
            <?php else:?>
                ---
            <?php endif;?>
            </td>
            <td class="actions">
                <?php if(!empty($deleted) && $deleted) :?>
                    <a class="btn btn-sm btn-primary"><span><i class="glyphicon glyphicon-refresh"></i> Restaurer</span></a>
                <?php else :?>
                    <a href="<?=Url::to(['houses/view', 'id'=>$house['referenceNumber']]);?>" class="btn btn-sm btn-info"><span><i class="glyphicon glyphicon-eye-open"></i> Consulter</span></a>
                    <a href="<?=Url::to(['houses/update', 'id'=>$house['referenceNumber']]);?>" class="btn btn-sm btn-warning"><span><i class="glyphicon glyphicon-pencil"></i> Modifier</span></a>
                    <a class="btn btn-sm btn-danger deleteHouse" data-ref="<?=$house['referenceNumber'];?>"><span><i class="glyphicon glyphicon-trash"></i> Supprimer</span></a>                    
                <?php endif;?>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<script src="<?=Url::base()?>/js/houses.js"></script>

backend/views/houses/create.php
<?php
    use yii\helpers\Url;
    $this->title = 'Ajouter un nouveau logement';
    $model->disponibility = date('d/m/Y');
?>
<div class="container-fluid">
    <!--div class="block-header">
        <h2><?=$this->title;?></h2>
    </div-->
    <!-- Basic Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        <?=$this->title;?>
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="<?=Url::to(['houses/index']);?>" title="Liste de tous les logements">Liste</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                    <?=Yii::$app->controller->renderPartial('_form', [
                        'data' => $data,
                        'model' => $model,
                        'active' => false
                    ]);?>
                </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
</div>

backend/views/houses/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\helpers\Url;
use common\components\ApiHelper;

$this->title = 'Logements disponibles';
/*echo '<pre>';
print_r($results);
echo '<pre>';
exit();*/
?>
<div class="container-fluid">
    <!--div class="block-header">
        <h2><?=$this->title;?></h2>
    </div-->
    <!-- Basic Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        <?=$this->title;?>
                        <small>Tous les logements sont listés dans cette section</small>
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="<?=Url::to(['houses/create']);?>" title="Ajouter un nouveau logement">Nouveau</a></li>
                                <li><a href="javascript:void(0);" id="list-active">Active</a></li>
                                <li><a href="javascript:void(0);" id="list-unactive">Non Active</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body table-responsive">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs tab-nav-right" role="tablist">
                        <li role="presentation" class="active"><a href="#home" id="tab-home" data-toggle="tab">TOUT (<?=count($allHouses)?>)</a></li>
                        <li role="presentation"><a href="#available" id="tab-available" data-toggle="tab">DISPONIBLE (<?=count($activeProperties)?>)</a></li>
                        <li role="presentation"><a href="#awaiting" id="tab-awaiting" data-toggle="tab">EN ATTENTE (<?=count($notActiveProperties)?>)</a></li>
                        <li role="presentation"><a href="#archive" id="tab-archive" data-toggle="tab">ARCHIVE (<?=count($deletedProperties)?>)</a></li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="home">
                            <b>Liste de tous les logements</b>
                            <?=Yii::$app->controller->renderPartial('_listhouse', [
                                'houses' => $allHouses
                            ]);?>                                     
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="available">
                            <b>Liste des logements disponibles</b>
                            <?=Yii::$app->controller->renderPartial('_listhouse', [
                                'houses' => $activeProperties
                            ]);?>                                 
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="awaiting">
                            <b>Liste des logements en attente</b>
                            <?=Yii::$app->controller->renderPartial('_listhouse', [
                                'houses' => $notActiveProperties
                            ]);?>                                    
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="archive">
                            <b>Liste des logements archivés</b>
                            <?=Yii::$app->controller->renderPartial('_listhouse', [
                                'houses' => $deletedProperties,
                                'deleted' => true
                            ]);?>                                    
                        </div>
                    </div>                            
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
</div>

backend/views/houses/update.php
<?php
    use yii\helpers\Url;
    use common\models\House;
    
    $this->title = 'Modifier les informations du logement <b>#' . $model->referenceNumber . '</b>';
    //fix disponibility
    if($model->disponibility == House::HOUSE_AVAILABLE) {
        $model->disponibility = date('d/m/Y');
    }
?>
<div class="container-fluid">
    <!--div class="block-header">
        <h2><?=$this->title;?></h2>
    </div-->
    <!-- Basic Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        <?=$this->title;?>
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="<?=Url::to(['houses/index']);?>" title="Liste de tous les logements">Liste</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                    <?=Yii::$app->controller->renderPartial('_form', [
                        'data' => $data,
                        'model' => $model,
                        'active' => true
                    ]);?>
                </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
</div>
<script type="text/javascript">
    //auto-select housing type
    $('#select-housing-type option').filter(function () { 
        return $(this).text() == "<?=$model->housingType;?>"; 
    }).prop('selected', true);
    //auto-select town
    $('#select-town option').filter(function () { 
        return $(this).text() == "<?=$model->town;?>"; 
    }).prop('selected', true);
    //auto-select housing type
    $('#select-zone option').filter(function () { 
        return $(this).text() == "<?=$model->zone;?>"; 
    }).prop('selected', true);
    //auto-select radius
    $('#select-radius option').filter(function () { 
        return $(this).text() == "<?=$model->radius;?>"; 
    }).prop('selected', true);    
</script>   

backend/views/houses/view.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;
$this->title = 'Details du logement : #' . $house['referenceNumber'];
$agent_contact = (!empty($house['contact'])) ? $house['contact'] : [];
use common\components\ApiHelper;

if(!empty($house['rentDeposit']) && $house['rentDeposit'] != 0) {
    $nombre_payment_mode = ceil($house['rentDeposit'] / $house['price']);
}
?>
       <div class="container-fluid">
            <!--div class="block-header">
                <h2><?=$this->title;?></h2>
            </div-->
            <!-- Basic Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                <?=$this->title;?>
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="<?=Url::to(['houses/index']);?>" title="Voir tous les logements">Logements</a></li>
                                        <li><a href="<?=Url::to(['houses/update', 'id'=>$house['referenceNumber']]);?>" title="Modifier les informations">Modifier</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th style="width: 220px">#</th>
                                        <th>Détails</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><?php if(count($house['pictures'])>1):?>Photos<?php else:?>Photo<?php endif;?></td>
                                        <td>
                                            <?php if(!empty($house['pictures'])):?>
                                                <?php foreach($house['pictures'] as $key=>$picture):?>                                             
                                                        <img src="<?= ApiHelper::HOST_URL . ApiHelper::HOUSE_UPLOAD_PATH . SYS_DIRECTORY_SEPARATOR . $house['referenceNumber'];?>/<?= !empty($house['pictures'][$key]) ? $house['pictures'][$key] : '';?>" style="width:175px; height:120px; border: 5px solid silver; border-radius: 5px;"/>
                                                <?php endforeach;?>
                                            <?php else :?>
                                                Aucune Image disponible
                                            <?php endif;?>                                                
                                        </td>
                                    </tr>                                      
                                    <tr>
                                        <td>Référence</td>
                                        <td><?=$house['referenceNumber'];?></td>
                                    </tr>                                     
                                    <tr>
                                        <td>Titre</td>
                                        <td><?=$house['titel'];?></td>
                                    </tr>
                                    <tr>
                                        <td>Description</td>
                                        <td><?=$house['description'];?></td>
                                    </tr> 
                                    <tr>
                                        <td>Description Additionel</td>
                                        <td><?=$house['additionalInfo'];?></td>
                                    </tr>                                     
                                    <tr>
                                        <td>Type de Logement</td>
                                        <td><?= ucfirst($house['housingType']);?></td>
                                    </tr>   
                                     <tr>
                                        <td>Douche Interne</td>
                                        <td><?= ($house['shower'] == 'interne') ? 'Oui' : 'Non';?></td>
                                    </tr>                                    
                                    <tr>
                                        <td>Nombre de Pièces</td>
                                        <td><?= ucfirst($house['roomCount']);?></td>
                                    </tr>                                     
                                    <tr>
                                        <td>Addresse</td>
                                        <td><?=$house['zone'];?>, <?=$house['town'];?></td>
                                    </tr>                                     
                                    <tr>
                                        <td>Prix</td>
                                        <td><?=$house['price'];?> <?= Yii::$app->params['localeCurrency'];?>/<?=$house['paymentMode'];?></td>
                                    </tr>  
                                    <tr>
                                        <td>Avance</td>
                                        <td><?=$house['rentDeposit'];?> <?= Yii::$app->params['localeCurrency'];?> (<?= (isset($nombre_payment_mode)) ? $nombre_payment_mode . ' ' . $house['paymentMode'] : '';?>)</td>
                                    </tr>    
                                    <tr>
                                        <td>Avance Electricité</td>
                                        <td><?=$house['electricityDeposit'];?> <?= Yii::$app->params['localeCurrency'];?></td>
                                    </tr>   
                                    <tr>
                                        <td>Type de Compteur</td>
                                        <td><?= ucfirst($house['electricityCounterType']);?></td>
                                    </tr> 
                                    <tr>
                                        <td>Agent</td>
                                        <td>
                                            <?php if(!empty($agent_contact)) : ?> 
                                            <div>
                                                Nom Complet : <?=$agent_contact['firstName'];?> <?=$agent_contact['surName'];?>                                                                                       
                                            </div>
                                            <div>
                                                Téléphone : <?=$agent_contact['telefonNr'];?>
                                            </div>
                                            <div>
                                                Email : <?=$agent_contact['email'];?>
                                            </div>
                                            <?php else:?>
                                                ---
                                            <?php endif;?>     
                                        </td>
                                    </tr>                                     
                                    <tr>
                                        <td>Ajouté le :</td>
                                        <td><?= ucfirst($house['publicationDate']);?></td>
                                    </tr>                                     
                                </tbody>
                            </table>
                            <a class="btn btn-primary" href="<?=Url::to(['houses/index']);?>"><< Retour</a>                                                
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Table -->         
        </div>