backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\components\ApiHelper;
use common\components\UserApiLoggedFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class' => UserApiLoggedFilter::className(),
                'only' => ['logout', 'index'],
            ],            
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                        //'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = 'login';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //var_dump($model);
            //exit();
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {       
        //unvalidate token via api
        //ApiHelper::logout();
        
        //logout user throughout system
        Yii::$app->user->logout();

        //redirect to login page
        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use linslin\yii2\curl;
use common\components\ApiHelper;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\SearchForm;
use app\components\FrontendSetting;
use common\components\UserApiLoggedFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public $enableCsrfValidation = false;
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class' => UserApiLoggedFilter::className(),
                'only' => ['index', 'contact'],
            ],            
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'registration'],
                'rules' => [
                    [
                        'actions' => ['registration'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        //get search data
            $searchData = ApiHelper::buildSearchData();

        //get recent properties
            $recentProperties =  ApiHelper::getLatestProperties();

        //get housing types count
            $housingTypeCounts =  ApiHelper::getHousingTypeCount();

        //display houses configuration
            $displayConfigurations = $this->propertyDisplayConfiguration();
            
        //model represent search form
            $searchModel = new SearchForm;
            $searchModel->publicationDate = FrontendSetting::SEARCH_DEFAULT_PUBLICATION_DATE;

        return $this->render('index', [
            'data' => $searchData,
            'houses' => $recentProperties,
            'displayConfigurations' => $displayConfigurations,
            'housingTypeCounts' => $housingTypeCounts,
            'searchModel' => $searchModel
        ]);
    }
    /**
     * 
     */
    public function actionTestEmail() {
        Yii::$app->mailer->compose()
                   ->setTo("gkpomasse@gmail.com")
                   ->setFrom("aide@beninimmobilier.com")
                   ->setSubject("Test")
                   ->setTextBody("Test contact")
                   ->send();       
    }

    /**
     * @return array
     */
    public function propertyDisplayConfiguration() {
        return [
            [
                "delay" => ".2s",
            ],
            [
                "delay" => ".4s",
            ],
            [
                "delay" => ".6s",
            ],
            [
                "delay" => ".2s",
            ],
            [
                "delay" => ".4s",
            ],
            [
                "delay" => ".6s",
            ],
            [
                "delay" => ".4s",
            ],
        ];
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            Yii::$app->session->setFlash('success', 'Bienvenue ' . Yii::$app->user->identity->surName . ' ' . Yii::$app->user->identity->firstName . ',<br/> Vous êtes maintenant connecté.');
            return $this->goHome();                  
        } else {
            if(Yii::$app->request->isPost)
            {//means that something wrong
                Yii::$app->session->setFlash('error', $model->getFirstError("password"));
            }
            $model->password = '';//reset password

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        //logout message
        Yii::$app->session->setFlash('notice', 'Vous êtes maintenant déconnecté.');

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();        
        if ($model->load(Yii::$app->request->post())) {
            $model->subject = FrontendSetting::CONTACT_PAGE_SUBJECT_TEXT;
            \Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->validate()) {//success form validation                
                if(isset($_POST['g-recaptcha-response']) && !empty($_POST['g-recaptcha-response'])) {
                    //your site secret key
                    $secret = '6LdC7EsUAAAAABJYpuTwVNKGtWPTTlympzlxHFOM';
                    //get verify response data
                    $c = curl_init('https://www.google.com/recaptcha/api/siteverify?secret='.$secret.'&response='.$_POST['g-recaptcha-response']);
                    curl_setopt($c, CURLOPT_RETURNTRANSFER, 1);
                    $verifyResponse = curl_exec($c);
                    $responseData = json_decode($verifyResponse);
                    if(!empty($responseData) && $responseData->success) {
                        try
                        {
                            $model->sendEmail(Yii::$app->params['contactEmail']);
                            //send success mail
                                /*Yii::$app->mailer->compose()
                                    ->setTo($model->email)
                                    ->setFrom([Yii::$app->params['contactEmail'] => Yii::$app->name])
                                    ->setSubject("Requête reçu avec succès.")
                                    ->setTextBody("Salut, " . $model->nom . ' ' . $model->prenom . "<br/> Votre requête est en cours de traitement. Merci de patienter!")
                                    ->send(); */
                            //
                            $responseArray = [
                                'type' => 'success',
                                'message' => "Everything went well!"
                            ];
                        } catch (\Exception $e) {
                            $responseArray = [
                                'type' => 'danger',
                                'message' => $e->getMessage()
                            ];
                        }

                        if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
                                return $responseArray;
                        } else {
                                echo $responseArray['message'];
                        }
                    } else {
                        $errorMessage = 'Robot verification failed, please try again.';
                        return [
                                'type' => 'danger',
                                'message' => $errorMessage
                        ];
                    }				
                } else {
                    $errorMessage = 'Please click on the reCAPTCHA box.';
                    return [
                            'type' => 'danger',
                            'message' => $errorMessage
                    ];				
                }
            } else {//return error message
                $errorMessage = 'Un Problème est survenu durant la soumission du formulaire!';
                return [
                        'type' => 'danger',
                        'message' => $errorMessage
                ];				
            }                
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);                
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionRegistration()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->signup()) {
                $login = new LoginForm();
                $login->username = $model->telephoneNr;
                $login->password = $model->password;
                if ($login->login()) {
                    Yii::$app->session->setFlash('success', 'Bienvenue ' . Yii::$app->user->identity->surName . ' ' . Yii::$app->user->identity->firstName . ',<br/> Vous êtes maintenant connecté.');
                    return $this->goHome();
                }

frontend/views/site/_recents.php
<?php
/**
 * @author Ghislain KPOMASSE
 * Date: 01/04/2018
 * Time: 21:28
 */
use yii\helpers\Url;
use common\components\ApiHelper;
?>
<?php foreach ($houses as $key=>$house) :?>
    <div id="recent-property" class="col-sm-12 col-lg-4 wow fadeInUp" data-wow-delay="<?=$displayConfigurations[$key]['delay'];?>">
        <div class="thumbnail"><a class="img-link" href="<?= Url::to(["houses/view", 'id'=>$house['referenceNumber']]);?>"><img src="<?= ApiHelper::HOST_URL . ApiHelper::HOUSE_UPLOAD_PATH . SYS_DIRECTORY_SEPARATOR . $house['referenceNumber'];?>/<?= !empty($house['pictures'][0]) ? $house['pictures'][0] : '';?>" alt="" width="370" height="250"/><span class="thumbnail-price"><?= $house['price'];?> <?= Yii::$app->params['localeCurrency'];?>/<span class="mon"><?= $house['paymentMode'];?></span></span></a>
            <div class="caption">
                <h4><a href="<?= Url::to(["houses/view", 'id'=>$house['referenceNumber']]);?>"><?= $house['titel'];?></a></h4>
                <ul class="describe-1">
                    <li><span class="icon icon-sm icon-darker material-icons-location_city"></span> <?= ucfirst($house['housingType']);?></li>
                    <li><span class="icon icon-sm icon-darker hotel-icon-05"></span><?= \app\components\Utils::pluralWords( $house['roomCount'], 'Pièce');?></li>  
                </ul>
                <ul class="describe-2" style="margin-left: 25px;">
                    <li>
                        <span class="icon icon-sm icon-darker material-icons-place" style="margin-left: -7px; font-size: 35px;"></span> <?= ucfirst($house['town']);?>
                    </li> 
                    <?php if(!empty($house['roomSize']) || $house['roomSize'] > 0):?>                             
                    <li>
                        <span class="icon-square">
                            <svg x="0px" y="0px" viewbox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve">
                              <g>
                                <path d="M3.6,75.7h3.6V7.3l85.7-0.1v85.3l-16.7-0.1l0-16.7c0-0.9-0.4-1.9-1-2.5c-0.7-0.7-1.6-1-2.5-1h-69V75.7h3.6                      H3.6v3.6H69L69,96c0,2,1.6,3.6,3.6,3.6l23.8,0.1c1,0,1.9-0.4,2.5-1c0.7-0.7,1-1.6,1-2.5V3.6c0-1-0.4-1.9-1-2.5                      c-0.7-0.7-1.6-1-2.5-1L3.6,0.1C1.6,0.2,0,1.7,0,3.7v72c0,0.9,0.4,1.9,1,2.5c0.7,0.7,1.6,1,2.5,1V75.7z"></path>
                                <path d="M38.1,76.9v-9.5c0-1.3-1.1-2.4-2.4-2.4c-1.3,0-2.4,1.1-2.4,2.4v9.5c0,1.3,1.1,2.4,2.4,2.4                      C37,79.3,38.1,78.2,38.1,76.9"></path>
                                <path d="M38.1,50.7V15c0-1.3-1.1-2.4-2.4-2.4c-1.3,0-2.4,1.1-2.4,2.4v35.7c0,1.3,1.1,2.4,2.4,2.4                      C37,53.1,38.1,52.1,38.1,50.7"></path>
                                <path d="M2.4,38.8h33.3c1.3,0,2.4-1.1,2.4-2.4c0-1.3-1.1-2.4-2.4-2.4H2.4c-1.3,0-2.4,1.1-2.4,2.4                      C0,37.8,1.1,38.8,2.4,38.8"></path>
                                <path d="M35.7,46h31c1.3,0,2.4-1.1,2.4-2.4c0-1.3-1.1-2.4-2.4-2.4h-31c-1.3,0-2.4,1.1-2.4,2.4                      C33.3,44.9,34.4,46,35.7,46"></path>
                                <path d="M78.6,46h16.7c1.3,0,2.4-1.1,2.4-2.4c0-1.3-1.1-2.4-2.4-2.4H78.6c-1.3,0-2.4,1.1-2.4,2.4                      C76.2,44.9,77.3,46,78.6,46"></path>
                                <path d="M78.6,46h16.7c1.3,0,2.4-1.1,2.4-2.4c0-1.3-1.1-2.4-2.4-2.4H78.6c-1.3,0-2.4,1.1-2.4,2.4                      C76.2,44.9,77.3,46,78.6,46"></path>
                                <path d="M81,43.6v-7.1c0-1.3-1.1-2.4-2.4-2.4c-1.3,0-2.4,1.1-2.4,2.4v7.1c0,1.3,1.1,2.4,2.4,2.4                      C79.9,46,81,44.9,81,43.6"></path>
                                <path d="M81,43.6v-7.1c0-1.3-1.1-2.4-2.4-2.4c-1.3,0-2.4,1.1-2.4,2.4v7.1c0,1.3,1.1,2.4,2.4,2.4                      C79.9,46,81,44.9,81,43.6"></path>
                              </g>
                            </svg>
                        </span>                                
                        <?= $house['roomSize'];?>m²
                    </li>  
                    <?php endif;?>
                </ul>
            </div>
        </div>
    </div>
<?php endforeach;?>

frontend/views/site/_search.php
<?php
/**
 * @author Ghismaon KPOMASSE.
 * Date: 01/04/2018
 * Time: 21:22
 */
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

$housingTypes = $data['housingTypeOptions'];//type de logement
$rowsCountOptions = $data['rowsCountOptions'];//nbre de pièces
$townOptions = $data['townOptions'];//town
$rowsZoneOptions = $data['rowsZoneOptions'];//zone
$rowsRadiusOptions = $data['rowsRadiusOptions'];//rayon
$rowspublicationOptions = $data['rowspublicationOptions'];//publications date

?>
<h3><?= \Yii::t('app', "Chercher une Maison / Appartement");?></h3>

<?php $form = ActiveForm::begin([
    'id' => "form-house-search",
    'action' => Yii::$app->urlManager->createUrl("houses/search"),
    'options' => [
        'class' => "form-variant-1",
    ]
]); ?>
<div class="row">
    <div class="col-md-6">
        <label for="select-1"><?= \Yii::t('app', "TYPE DE LOGEMENT")?></label>
        <?= Html::activeDropDownList($searchModel, 'housingType', ArrayHelper::map($housingTypes, 'key', function($item) {return ucfirst($item['value']);}), [
            'prompt'=>'Toutes les offres', 
            'id'=>'select-1',
            'data-selected'=>$searchModel->housingType,
            'class' => 'rd-mailform-select'
        ]) ?>        
    </div>
    <div class="col-md-6">
        <label for="select-2"><?= \Yii::t('app', "TAILLE")?></label>
        <?= Html::activeDropDownList($searchModel, 'roomCount', ArrayHelper::map($rowsCountOptions, 'key', function($item) {return ucfirst($item['value']);}), [
            'prompt'=>'Nombre de pièces', 
            'id'=>'select-2',
            'data-selected'=>$searchModel->roomCount,
            'class' => 'rd-mailform-select'
        ]) ?>         
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <label for="select-3"><?= \Yii::t('app', "VILLE")?></label>
        <?= Html::activeDropDownList($searchModel, 'town', ArrayHelper::map($townOptions, 'key', function($item) {return ucfirst($item['value']);}), [
            'prompt'=>'Toutes les villes', 
            'id'=>'select-3',
            'data-selected'=>$searchModel->town,
            'class' => 'rd-mailform-select'
        ]) ?>        
    </div>
    <div class="col-md-3">
        <label for="select-4"><?= \Yii::t('app', "ZONE")?></label>
        <?= Html::activeDropDownList($searchModel, 'zone', ArrayHelper::map($rowsZoneOptions, 'key', function($item) {return ucfirst($item['value']);}), [
            'prompt'=>'Toutes les zones', 
            'id'=>'select-4',
            'data-selected'=>$searchModel->zone,
            'class' => 'rd-mailform-select'
        ]) ?>         
    </div>
    <div class="col-md-3">
        <label for="select-6"><?= \Yii::t('app', "RAYON")?></label>
        <?= Html::activeDropDownList($searchModel, 'radius', ArrayHelper::map($rowsRadiusOptions, 'key', function($item) {return ucfirst($item['value']);}), [
            'prompt'=>'Dans un rayon de', 
            'id'=>'select-6',
            'data-selected'=>$searchModel->radius,
            'class' => 'rd-mailform-select'
        ]) ?>         
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group width-1" style="width: 100%">
            <label for="range-1"><?= \Yii::t('app', "PRIX (FCFA)")?><br></label>
            <?= Html::activeTextInput($searchModel, 'minPrice', ['id'=>"range-1", 'class' => 'rd-range-input-value rd-range-input-value-1']);?>
            <?= Html::activeTextInput($searchModel, 'maxPrice', ['id'=>"range-2", 'class' => 'rd-range-input-value rd-range-input-value-2']);?>
            <div class="rd-range" data-min="5000" data-max="200000" data-start="[5000, 200000]" data-step="500" data-tooltip="true" data-min-diff="100" data-input=".rd-range-input-value-1" data-input-2=".rd-range-input-value-2"></div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group width-1" style="width: 100%">
            <label for="range-3"><?= \Yii::t('app', "SURFACE (m²)")?><br></label>
            <?= Html::activeTextInput($searchModel, 'minSurface', ['id'=>"range-3", 'class' => 'rd-range-input-value rd-range-input-value-3']);?>
            <?= Html::activeTextInput($searchModel, 'maxSurface', ['id'=>"range-4", 'class' => 'rd-range-input-value rd-range-input-value-4']);?>
            <div class="rd-range" data-min="5" data-max="1000" data-start="[5, 1000]" data-step="5" data-tooltip="true" data-min-diff="2" data-input=".rd-range-input-value-3" data-input-2=".rd-range-input-value-4"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group width-2" style="width: 100%">
            <label for="select-8"><?= \Yii::t('app', "MOTS CLES")?></label>
            <?= Html::activeTextInput($searchModel, 'keyword', ["id"=>"keyword", "placeholder" => "Sanitaire, Meublé ..."]);?>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group width-2" style="width: 100%">
            <label for="select-5"><?= \Yii::t('app', "DATE DE PUBLICATION")?></label>
            <?= Html::activeDropDownList($searchModel, 'publicationDate', ArrayHelper::map($rowspublicationOptions, 'key', function($item) {return ucfirst($item['value']);}), [
                'id'=>'select-5',
                'data-selected'=>$searchModel->publicationDate,
                'class' => 'rd-mailform-select',
                'data-calendar' => ''
            ]) ?>             
        </div>
    </div>
</div>
<div class="row">
    <button class="btn btn-md btn-primary"><?= \Yii::t('app', "Rechercher")?></button>
</div>
<?php ActiveForm::end(); ?>

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $name;
?>
<!--Section 404-->
<section class="section-height section-height-1 bg-image bg-image-1 section-middle">
  <div class="container z-index">
    <div class="jumbotron jumbotron-mod-1 text-center text-md-left">
      <h1><?= Html::encode($this->title) ?></h1>
          <div class="alert alert-danger">
              <?= nl2br(Html::encode($message)) ?>
          </div>
      <a class="btn btn-transparent btn-md" href="<?=Url::to(['site/index']);?>">Revenir à l'acceuil</a>
    </div>
  </div>
</section>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Se Connecter';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    #login-form a {
        color: #FFF;
    }
    
    #login-form input[type="checkbox"]{
        width: 25px;
        height: 20px;
        vertical-align: bottom;
    }
</style>    
<!--Section Login-->
<section class="section-height-mod-1 bg-image bg-image-1 section-middle">
    <div class="container z-index">
        <div class="row justify-content-center justify-content-lg-start">
            <div class="col-sm-12 col-md-8 col-xl-5">
                <div class="jumbotron jumbotron-mod-1 text-center text-lg-left">
                    <h1><?= Html::encode($this->title) ?></h1>
                    <?php 
                        $form = ActiveForm::begin([
                            'id' => 'login-form', 
                            'fieldConfig' => ['template' => "{label}\n{input}\n{hint}"]
                        ]);
                    ?>

                    <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'required' => true]) ?>

                    <?= $form->field($model, 'password')->passwordInput(['required' => true]) ?>

                    <?= $form->field($model, 'rememberMe')->checkbox() ?>

                    <div style="color:#999;margin:1em 0">
                        <?= Html::a('Mot de Passe oublié ?', ['site/request-password-reset']) ?>.
                    </div>
                    <div style="color:#999;margin:1em 0">
                        <?= Html::a('Pas de Compte ?', ['site/registration']) ?>.
                    </div>                    

                    <div class="form-group">
                        <?= Html::submitButton('Connexion', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</section>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Inscription';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="section-height-mod-1 bg-image bg-image-1 section-middle">
    <div class="container z-index">
        <div class="row justify-content-center justify-content-lg-start">
            <div class="col-md-8">
                <div class="jumbotron jumbotron-mod-1 text-center text-lg-left">
                    <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
                    <h1><?= Html::encode($this->title) ?></h1>

                    <div class="row" style="margin:0;padding:0">
                        <div class="col-lg-6">
                            <?= $form->field($model, 'surName')->textInput(['autofocus' => true, 'required' => true, 'placeholder' => 'Votre nom...']) ?>                           
                        </div>
                        <div class="col-lg-6">
                            <?= $form->field($model, 'firstName')->textInput(['required' => true, 'placeholder' => 'Votre prénom...']) ?>
                        </div>
                    </div>
                    <div class="row" style="margin:0;padding:0">
                        <div class="col-lg-6">
                            <?= $form->field($model, 'telephoneNr')->textInput(['required' => true, 'placeholder' => 'Votre numéro']) ?>                         
                        </div>
                        <div class="col-lg-6">
                            <?= $form->field($model, 'email')->textInput(['required' => true, 'type' => 'email', 'placeholder' => 'Votre adresse Email...']) ?>
                        </div>
                    </div>     
                    <div class="row" style="margin:0;padding:0">
                        <div class="col-lg-6">
                            <?= $form->field($model, 'password')->passwordInput(['required' => true, 'placeholder' => 'Votre mot de passe...']) ?>                       
                        </div>
                        <div class="col-lg-6">
                            <?= $form->field($model, 'confirmationPassword')->passwordInput(['required' => true, 'placeholder' => 'Confirmation du mot de passe...']) ?>
                        </div>
                    </div>                     
                    <div class="form-group" style="margin-left:14px;">
                        <?= Html::submitButton('Je m\'inscris', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>        
    </div>
</section>